### ISSUE TITLE
Rewrite introduction

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#16]
Write an educational introduction about ultrasound imaging, basic acoustics and technics

Indicative due date : April 30th, 2017

Criteria to close the issue :

- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/) with the new introduction.
- To edit the gitbook, fork the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : introduction/new_introduction.md
if you use latex formulas, please put these between DOUBLE $$ : $$\sigma$$ for example
if you use latex formulas, please check the compatibility with the gitbook's plugin BEFORE making a pull request. A useful link for this : https://khan.github.io/KaTeX/
- Make a pull request refering to this issue

**Comment by Aurelie-Mutschler** [comment]
Discussed with @Halipster : 
On top of the general introduction, there are two distinct parts

- the production of the pulse:
pulser, motor & listening time related to the speed of sound in water, beam focalisation depending on the type of transducer

- the received signal processing:
1. propagation of acoustic waves in media: refexion, refraction, attenuation
2. transducer & piezoelectricity (explain why three transducers)
3. TGC
4. ADC
5. envelope detection
6. scan conversion

I begin from 6, you begin from 1, meet me halfway ;-)
![img_20170507_191535](https://cloud.githubusercontent.com/assets/10047375/25783325/adecdeb0-335a-11e7-9109-8c01111209c9.jpg)

**Comment by Aurelie-Mutschler** [comment]
@Halipster your flowchart doesn't build on the gitbook, I think you forgot to add the plugin in the book.json. Can you give me the name of the plugin ?

**Comment by halipster** [comment]
mermaid 
gitbook-plugin-mermaid

**Comment by Aurelie-Mutschler** [comment]
@halipster Apolline is in da place to make an awesome introduction ;-)

**Comment by Aurelie-Mutschler** [comment]
@ApollineF here are some remarks about the introduction:

- in the explanations, there are some sentences like "The acoustic impedance of is the product of the density and the sound speed". Maybe we could include some equations to illustrate ? In the gitbook we have a plugin which allows to write formulas with LaTeX syntax : https://users.dickinson.edu/~richesod/latex/latexcheatsheet.pdf
I added in this issue's description some instructions to use the plugin.

- maybe we could also add some schemes in the beginning, what do you think?

- the last part about the acquisition and processing pipeline is nice! could you refine and detail a bit more the explanations (including the first paragraph on top of the scheme) ? I think there's a discrepancy between the explanations about the physics principles and this part that seems a bit more expeditious and might not be easy to read for non-experts

Besides, the introduction is great - thanks @halipster @ApollineF !

**Comment by Aurelie-Mutschler** [comment]
@ApollineF if you want to add some schemes please do it before Friday because someone will improve them during the weekend :wink:

**Comment by ApollineF** [comment]
Hi ! Alright, it will be done before Friday. Is it a problem if some of the schemes I've added so far come from other web pages ? Do I need to draw them all or should I just write the link below ?

**Comment by Aurelie-Mutschler** [comment]
No it's ok don't worry ;)
