### ISSUE TITLE
Merge "hacking guide" parts in the suited sections of the gitbook

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#35]
Let's :
1. Create a "get started" section with two sub-sections ("Hacking guide" + "set up you echOpen lab" from the starterkit) here "hacking guide" should gather only the information that is necessary to install the "dev" version of the app (?)
2. Dispatch the information from the "old" hacking guide to the best suited sections :
- installation, running the app, echopen's virtual machine should go to "stable release/installing the app"
- mockup - UX will be a task for next iteration (this has to be written in the "preparing captech" file)
- the other challenges should be re-structured so that contributors can easily take part --> those ones will go in the dedicated "challenges" section
- "scan conversion" should be splitted into a pedagogical part that will be integrated in the technical introduction, and an app-related part that should go in the documentation

Indicative due date : June 1st, 2017

Criteria to close the issue :

- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown files
- Make a pull request refering to this issue

**Comment by Aurelie-Mutschler** [comment]
ping @benchoufi I propose that I dispatch your hacking guide's parts in the different sections of the gitbook, then I let you review my pull request ? I will unplug the current version of the hacking guide when it's done. But I'll keep a track of the .md files so you can recover the informations related to v2.0.0 when needed. What do you think ?

**Comment by Aurelie-Mutschler** [comment]
still work to be done - I think some parts should be pushed in the software documentation (the ones describing current implementations for v3.0.0, for example as regards scan conversion, and also the constants.md)
--> @benchoufi @clecoued I let you update the software documentation accordingly, as the PR has not been accepted yet

**Comment by benchoufi** [comment]
ok we'll talk about it with @clecoued. Perhaps, we will add in the hacking guide some extracts of this constants.md file that is needed, for example when detailing the scan conversion - in order to get the reader focus and throw him to the soft doc repo for an exhaustive presentation
