### ISSUE TITLE
Bibliography : How to assess the image quality

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#4]
Gather information about state-of-the-art ways of assessing the quality of an ultrasound image.

Indicative due date : April 30th, 2017

Criteria to close the issue :

- identify a set of metrics that will be used to evaluate the image quality of the echOpen kit
- gather clear instructions about how to measure those metrics : needs for phantom, measurement technics, ...
- write a summary of the findings and include it in the prototyping gitbook.
- make a pull request refering to this issue

Some bibliography has already been carried out. You can find the references here : https://drive.google.com/drive/folders/0B8YU5qFDi1mDX2hnazlpTl9uSms

**Comment by kelu124** [comment]
As discussed, the first step by end of April is compiling the biblio and extract key learning.

**Comment by kelu124** [comment]
I've put the first notes on /inprogress/IMGQ_metrics.md
ping @soobash

**Comment by Aurelie-Mutschler** [comment]
thanks guys !
