### ISSUE TITLE
Translate frenglish to english :D

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#48]
in the Challenges/ section, translate sentences / paragraphs that are in french to english

Indicative due date : May 30th, 2017

Criteria to close the issue :

- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown files : challenges/*.md
- Make a pull request refering to this issue

**Comment by benchoufi** [comment]
done ;)
