### ISSUE TITLE
Correct typos / english

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#65]
Correct the typos and improve the wallstreet-english :D

Indicative due date : July 30th, 2017

Criteria to close the issue :

- To edit the gitbook, fork the repo : https://github.com/echopen/echopen_prototyping
- Edit the markdown files
- When you're done, make a pull request refering to this issue

**Comment by Aurelie-Mutschler** [comment]
@nfilipov you can go for it :slightly_smiling_face:

**Comment by nfilipov** [comment]
PR is here : https://github.com/echopen/echopen_prototyping/pull/83
