### ISSUE TITLE
Mobile App documentation upgrade

### ISSUE THREAD

**Issue by clecoued** [echopen/echopen_prototyping#66]
Here a list of all issues: 

* Clean Minute of meetings

* change GPU & real time processing challenge in order to get a more general challenge(multi filters, multi techno) 

* close challenge - Scan conversion,
   fix typo 

* migrate data format challenge to DICOMIZER challenge

* fill HETIC School challenge

* create new cards in Mobile app Projects  v4.0.0

* reorganize Mockup page

* finalize rendering pipeline with data stream quantification

* move "Current algo choice for scan-conversion" to another section "Technical choice"

issue from Beta testing -> 
in stable/requirements/specifications/mobile-app.md:
-- "... today, the frame-rate is 5 frames per second (fps)": I'm confused. Previous mentions were 2fps, then 90-100 (but only on mobile app, if I understand correctly). What is the currently achieved framerate ? Also, the last sentence, "In the current hardware configuration" is hanging without an end.
-- " -> clement for more details" this could be explicited with a @ , no ?

in stable/requirements/UX_design:
-- we open on an empty page again.
-- it looks like this is closely related to the previous section, right ?
-- images are HUGE :smile:

in stable/doc_pipeline.md:
-- the words in each block are cropped, but that could also be because of my browser ...

**Comment by Aurelie-Mutschler** [comment]
guys how is it going? ready for tomorrow as promised? 😀

**Comment by benchoufi** [comment]
hi there, @Aurelie-Mutschler everything have been made except challenges updates. We agreed that it was not compulsory for releasing. So @clecoued is going to review some details tomorrow and we are done ;) there are no pictos to say how much we are happy 100011100011

**Comment by Aurelie-Mutschler** [comment]
waiting for cleaning of challenges to close the issue ;-)

**Comment by Aurelie-Mutschler** [comment]
as decided in yesterday's meeting, we unplugged the challenges related to Android dev from the gitbook, but the source files are still available in the github repo in case you need it 😉 

WE'RE DONE! I REPEAT : WE'RE DONE ! 🎉
