### ISSUE TITLE
Write documentation for hardware

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#7]
Write full documentation for the version 3.0.0 prototype :

- updated block diagram
- synoptic diagram representing the modules (with clear references to modules + links to the github documentation of each module) and connections between them (direction of the signal transmission should be indicated)
- check that all the module descriptions are up-to-date and complete
- write an explicit description of the configuration, including the exhaustive description of the "default" tunings on each module (gain, ADC frequency, motor control...)
- mechanical scheme + description of the functioning
- characteristics of transducer
- link to the complete kit configuration in the PRJ_medtech-kit repo (the new prototype has to be created in the repo)

Indicative due date : April 10th, 2017

Criteria to close the issue :
- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/) with the software documentation.
- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : stable/doc_hardware.md
- Make a pull request refering to this issue

**Comment by kelu124** [comment]
For the synoptic diagram what do you think of graphviz? 
These can be automatically generated and propose different visualisations for say the interfaces (yellow), the input/output in green and the modules in blue =)
![](https://raw.githubusercontent.com/kelu124/echomods/master/include/sets/emulated.png)

and for detail within the hardware:

![](https://raw.githubusercontent.com/kelu124/echomods/master/goblin/source/blocks.png)

**Comment by Aurelie-Mutschler** [comment]
thanks for the great job @jerome2echopen !
