### ISSUE TITLE
Highlight contributors on the gitbook

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#72]
Highlight contributors on the gitbook:
- 1 dedicated page with all contributor's name at the beginning of the gitbook
- ask to each contributors how they want to be called, and to which sections/pages they contributed
--> write the contributors' names at the beginning of each section or page

Indicative due date : July 11th, 2017

Criteria to close the issue :

- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/)
- To edit the gitbook, fork the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : introduction/new_introduction.md
- Make a pull request refering to this issue

**Comment by ApollineF** [comment]
Hi guys ! 
I'm going to write a page dedicated to the contributors at the beginning of the Gitbook so could you please tell me how you want to be called and which section/pages you contributed to ? 
@benchoufi  @Olivierff @Aurelie-Mutschler @halipster @kelu124  @eiffel-fl @Bivi @GG23800  @clecoued @marshyski

**Comment by Aurelie-Mutschler** [comment]
I will handle this ;)

**Comment by Aurelie-Mutschler** [comment]
done : list of authors added to each page of the gitbook ;-)
