### ISSUE TITLE
Draw a global block diagram (hardware + software)

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#9]
Draw a global block diagram displaying the hardware + software functions, and explicit the data transfer protocol

Indicative due date : April 10th, 2017

Criteria to close the issue :

- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/) with the assembly guide.
- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : stable/stable.md
- Make a pull request refering to this issue

**Comment by Aurelie-Mutschler** [comment]
discussed with @clecoued 👍 
- one global functional bloc diagram not much detailed
- one scheme of the data processing pipeline

**Comment by Aurelie-Mutschler** [comment]
a scheme of the data processing pipeline has been done. waiting from updates of the scheme from @clecoued to close the issue 😉

**Comment by clecoued** [comment]
do we still need the data processing pipeline graph ?

**Comment by Aurelie-Mutschler** [comment]
I think so, no ?

**Comment by Aurelie-Mutschler** [comment]
@clecoued this becomes a bit urgent 😱

**Comment by Aurelie-Mutschler** [comment]
thanks @clecoued
